spring.application.name=UrlShortner

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortnerdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Server Configuration
server.port=9030

# Base URL Configuration
app.base-url=http://localhost:9030/